### ISSUE TITLE
Unstable output

### ISSUE THREAD

**Issue by projetmbc** [loopspace/tikzmark#18]
I'm not sure that `tikzmark` is guilty, but `latexmk main` on the following `main.tex` file throws the error `Latexmk: Maximum runs of latex reached without getting stable files`.

```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{tikzmark}

\newlength{\unitht}
\setlength{\unitht}{.8ex}

\newcommand{\nubpre}{usecase-A}
\newcommand{\nubdepth}{0}

\NewDocumentCommand{\nub}{mm}{%
  \tikzmark{a\nubpre#1} % 
    #2                  % 
  \tikzmark{b\nubpre#1} % 
  %
  \pgfmathsetmacro\nubvoffset{#1 - \nubdepth}%
  %
  \llap{
    \begin{tikzpicture}[
        remember picture,
        baseline = (current bounding box.north)
    ]
      \draw (pic cs:a\nubpre#1)            
              --++ (0,\nubvoffset*\unitht) 
              -|                           
            (pic cs:b\nubpre#1);           
    \end{tikzpicture}%
  }%
}


\begin{document}

\renewcommand{\nubdepth}{6}

$ \nub{1}{
    11 + \nub{2}{
      12 + \nub{3}{
        13 + \nub{4}{
          14 + \nub{5}{15 + 16} +
          17} +
        18} +
      19} +
    20}
= 31 \times 5
= 155$

\end{document}
```

**Comment by daleif** [comment]
It would probably be a good idea to link to Johns analysis https://tex.stackexchange.com/a/730337/3929, especially as he mentions that something pgf related is constantly changing in the aux file and thus a compilation can never be finalised. As your question is worded here, it requires knowledge of what `latexmk` is and does.

**Comment by projetmbc** [comment]
Good point!

**Comment by projetmbc** [comment]
John Collins has noted that commenting out the line `remember picture` resolves the problem : https://tex.stackexchange.com/users/8495/john-collins .

**Comment by loopspace** [comment]
I've answered on TeX-SX: https://tex.stackexchange.com/a/730524/86 (you've hopefully gotten a notification about that). For the record here, the issue is that the `tikzpicture` that _used_ the `tikzmark`s was missing its `overlay` option. Putting that back in resolves the problem.
