### ISSUE TITLE
\subnode captures wrong position with XeLaTeX

### ISSUE THREAD

**Issue by muzimuzhi** [loopspace/tikzmark#4]
MWE:
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{tikzmark}

\begin{document}

\begin{tikzpicture}[remember picture, overlay]
  \node[draw] (main node) {\subnode{subnode}{TEXT}};
  \draw[blue] (main node.center) circle (1ex);
  \draw[red] (subnode.center) circle (1ex);
\end{tikzpicture}

\end{document}
```

Output 1, compiled with `XeLaTeX`:
![image](https://user-images.githubusercontent.com/6376638/47261121-86e78600-d4fb-11e8-9a94-0e401fc6a5c0.png)

Output 2, compiled with `pdfLaTeX`:
![image](https://user-images.githubusercontent.com/6376638/47261184-771c7180-d4fc-11e8-9e52-d49d1b5cf526.png)

Explanation:
 - The blue circle denotes the center of `\node`,
 - the red circle denotes the center of `\subnode`, which should overlay the blue circle perfectly, and
 - the red circle is at the wrong position with `XeLaTeX`, while with `pdfLaTeX` everything works alright.

Some Investigation:
 - the size of subnode is correct, but the position is offset.
 - with `\subnode`, even the `\pgfsys@markposition` (see modified code below) marks different position between `pdfLaTeX` and `XeLaTeX`.
  ```latex
  % "here" captures wrong position
  \node[draw] (main node) {\pgfsys@markposition{here}\subnode{subnode}{TEXT}};

  % "here" captures right position, with tikzmark loaded but \subnode not used
    \node[draw] (main node) {\pgfsys@markposition{here}};
  ```

**Comment by loopspace** [comment]
There are issues with tikzmark and xelatex.  Some information is at https://tex.stackexchange.com/q/229500/86

It's on my list of things to figure out, if you (or anyone else) figures out what is going on before me then I would be happy to add in a solution.

**Comment by muzimuzhi** [comment]
Thanks for your response. Here is some info I get after reading the link you provided and the related still-open `pgf` issue (https://sourceforge.net/p/pgf/bugs/354/):

 - This problem is caused by the `pgf` backend driver for `dvipdfmx`, hence has nothing to do with `tikzmark`.
 - It is the `pgfsys-dvipdfmx.def` version `\pgfsys@hboxsynced` that caused the problem.
 - A workaround, which recovers the definition of `\pgfsys@hboxsynced` to the common driver version, is provided in [comment](https://sourceforge.net/p/pgf/bugs/354/#72e2) of that `pgf` issue page.

Since this is a `pgf`-related problem, not `tikzmark`, I will close this issue. May the above info helpful for others. And thanks again, for denoting the link to previous TeX.SX discussions.
