### ISSUE TITLE
minimum width in \tikzmarknode

### ISSUE THREAD

**Issue by jandhau** [loopspace/tikzmark#7]
I am following a suggestion made by Ulrike in her answer to [this](https://tex.stackexchange.com/questions/483488/tikzmarknode-and-vphantom-take-up-horizontal-space) TeX.SX question, to ask if the `minimum width` should not better be set to `0pt` insead of `1pt` in the `\tikzmarknode`

See the link for the particular use case where this became an issue. 

Thanks :)

**Comment by loopspace** [comment]
Fixed in 888ec38088d5a959dca38325c5dd0dbfcbbed2f0
